= Qorvo Double Pulse Testing on Tektronix MSO5/6 Oscilloscope Example" Software

ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

== Overview
This is a https://www.python.org[Python] script to perform a double pulse test (DPT) of a wide-bandgap transistors, like https://www.qorvo.com/[Qorvo]'s https://www.qorvo.com/feature/sic-power-products[SiC devices] or Gan, by using an installed AFG module on a Tektronix https://www.tek.com/en/products/oscilloscopes/6-series-mso[MSO6] or https://www.tek.com/en/products/oscilloscopes/5-series-mso[MSO5] oscilloscope.

This command-line script takes user inputs to generate DPT pulse sequence on your PC, to send it to an MSO5 or MSO6 scope, and to configure the scope for a DPT.

See our http://somewhere.tek.com[application note] for the detail.

The Windows **binary** is found in the https://github.com/Qorvo/DPT-on-MSO6/releases[release] page in the right pane.

== Licenses
IMPORTANT: Please kindly let us know when you find other licenses to be mentioned here.

* The source Python script code, writtne by Qorvo, is under the https://github.com/MasashiNogawa/DPT-on-MSO6/blob/main/LICENSE[license of Qorvo], and the compiled binary is also under the same license.
* The compiled binary is generated by the https://pyinstaller.org/[PyInstaller] and see the PyInstaller https://github.com/pyinstaller/pyinstaller/blob/develop/COPYING.txt[license].
* In the course of compiling the binary, some Python codes are archived. See the Python https://docs.python.org/3/license.html[licenses]. The binary is generated on the Python version 3.11.2.
* The software, both Python script code and binary, is calling the https://pyvisa.readthedocs.io/[PyVISA] library and see the PyVISA https://github.com/pyvisa/pyvisa/blob/main/LICENSE[license].

== Notes

[IMPORTANT]
====
* The Windows binary **IS NOT** a GUI program, start the program from a CUI terminal like cmd.exe or git bash.
* At first use of the software, it creats a copy of the LICENSE file in the same folder the program reside and requests to read the license, if no "LICENSE" file. From the second use and after, this won't happen as you keep the file.
* Both source code and binary are **AS-IS** base, please DO NOT expect any active support on this software.
====

== Dependencies / Libraries to be Installed on Your PC

* The PyVISA module, in the script, searches IVI library backends once the program invoked. See the https://pyvisa.readthedocs.io/en/latest/introduction/configuring.html#configuring-the-ivi-backend[detail]. We tested the code and binary with the https://www.ni.com/en-us/support/downloads/drivers/download.ni-visa.html[NI-VISA].
* The https://github.com/libusb/libusb[libusb] library enables a USB connection between your PC and the MSO scope. See the https://pyvisa.readthedocs.io/projects/pyvisa-py/en/latest/installation.html#usb-resources-usb-instr-raw[detail]. To use a USB I/F, please place a libusb file in your "PATH".

..end of README
